version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.12.0

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            echo "Running CircleCI"


workflows:
  version: 2
  common-build:
    jobs:
      - build:
